"""Add specifications field to Asset

Revision ID: c405f9bb700e
Revises: 7f2240ad9e9c
Create Date: 2025-02-25 16:53:09.523832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c405f9bb700e'
down_revision = '7f2240ad9e9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specifications', sa.String(length=500), nullable=True))
        batch_op.alter_column('location_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.alter_column('location_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('specifications')

    # ### end Alembic commands ###
