"""Add vendor and condition fields to Asset

Revision ID: c81cafcc97d2
Revises: c405f9bb700e
Create Date: 2025-02-25 18:07:19.587105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c81cafcc97d2'
down_revision = 'c405f9bb700e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('condition', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_column('condition')
        batch_op.drop_column('vendor')

    # ### end Alembic commands ###
